// public calss Tipos{
//   public static void main (String[] TiposPrimitivos){

// byte => 8 bits => -128 a 127 

// short => 16 bits => -32.768 a 32.767

// int => 32 bits => -2.147.483.648 a 2.147.483.647

// long => 64 bits => -9.223.372.036.854.775.808 a 9.223.372.036.854.775.807

// float => 32 bits => 1.4E-45 a 3.4028235E38     //precisão simples

// double => 64 bits => 4.9E-324 a 1.7976931348623157E308 //precisão dupla

// String => cadeia de caracteres => "texto", "nome", "frase" 

// char => repserenta um caractere => 'a', 'b', 'c', '1', '2', '3'
// char meuChar = 'a';
// meuChat='name';

// boolean => 1 bit => true ou false

// numeros decimais = 1.2, 3.4, 5.6, 7.8, 9.0
// 5.50
//   }

// }
// Nativos tipos primitivos em Java:
// byte b= 100;
// short s = 10000;
// int i=100000;
// long l=100000L;
// float f=230.47f;
// double d= 123.4;
// char c='W';
// String st="Fulano";
// boolean bo= false;
// boolean bo2=true;

if(bo2){
  System.out.println("verdadeiro");
}else{
  System.out.println("falso");
}